# -*- coding: utf-8 -*-
"""Otomatisasi Jadwal Bikom Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zL9KUel8gjMmhCIKJTG0eS031kid_n1s
"""

import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Alignment, Border, Side
import io

st.set_page_config(page_title="Penjadwalan Bimbingan Otomatis", layout="wide")
st.title("📅 Sistem Penjadwalan Bimbingan Komunal Otomatis")

# ==========================
# PARAMETER
# ==========================
st.sidebar.header("⚙️ Parameter Penjadwalan")

DURASI_PER_TIM = st.sidebar.number_input("Durasi per Tim (menit)", 10, 120, 20, 5)
MAKS_TIM_PER_DOSEN_PER_SESI = st.sidebar.number_input("Maks Tim per Dosen per Sesi", 1, 30, 12)
MAX_TABLE_PER_ROW = st.sidebar.number_input("Jumlah Tabel per Baris", 1, 10, 6)

OUTPUT_FILE = "jadwal_bikom.xlsx"

HARI_BIMBINGAN = {
    "Selasa": "Jam Kesediaan pada Selasa, 21 Januari 2025",
    "Rabu": "Jam Kesediaan pada Rabu, 22 Januari 2025",
}

# ==========================
# UPLOAD
# ==========================
file_tim = st.file_uploader("Upload File Excel Data Tim", type=["xlsx"])
file_dosen = st.file_uploader("Upload File Excel Data Dosen", type=["xlsx"])

if file_tim and file_dosen:
    df_tim = pd.read_excel(file_tim)
    df_dosen = pd.read_excel(file_dosen)

    st.success("File berhasil dibaca")

    # ==========================
    # FUNGSI JAM
    # ==========================
    def buat_slot(jam_mulai, jam_selesai, durasi):
        slot = []
        start = datetime.strptime(jam_mulai, "%H.%M")
        end = datetime.strptime(jam_selesai, "%H.%M")
        while start + timedelta(minutes=durasi) <= end:
            slot.append(f"{start.strftime('%H:%M')}-{(start + timedelta(minutes=durasi)).strftime('%H:%M')}")
            start += timedelta(minutes=durasi)
        return slot

    def parse_jam_per_sesi(jam_text):
        if pd.isna(jam_text) or str(jam_text).strip() == "Tidak Bersedia":
            return []
        sesi_list = []
        for bagian in str(jam_text).split(","):
            bagian = bagian.strip().replace("–", "-").replace("—", "-")
            if " - " not in bagian:
                continue
            mulai, selesai = bagian.split(" - ")
            sesi_list.append({
                "range": f"{mulai} - {selesai}",
                "slots": buat_slot(mulai, selesai, DURASI_PER_TIM)
            })
        return sesi_list

    def jam_mulai_sesi(sesi_range):
        return datetime.strptime(sesi_range.split(" - ")[0], "%H.%M")

    def hitung_sisa_jam(sesi_range, slot_terpakai):
        mulai, selesai = sesi_range.split(" - ")
        selesai_dt = datetime.strptime(selesai, "%H.%M")
        if not slot_terpakai:
            return sesi_range
        last_end = slot_terpakai[-1].split("-")[1]
        last_end_dt = datetime.strptime(last_end, "%H:%M")
        if last_end_dt >= selesai_dt:
            return None
        return f"{last_end_dt.strftime('%H:%M')} - {selesai}"

    if st.button("🚀 Proses Penjadwalan"):
        # ==========================
        # PROSES DOSEN
        # ==========================
        slot_dosen = {}
        for _, row in df_dosen.iterrows():
            slot_dosen[row["Nama Lengkap"]] = {
                "bidang": [b.strip() for b in row["Bidang PKM"].split(",")],
                "lokasi": row["Lokasi"],
                "jadwal": {
                    hari: parse_jam_per_sesi(row[kol])
                    for hari, kol in HARI_BIMBINGAN.items()
                    if kol in row and parse_jam_per_sesi(row[kol])
                }
            }

        # ==========================
        # PENJADWALAN
        # ==========================
        hasil = []
        jumlah_tim_dosen = {}

        for _, tim in df_tim.iterrows():
            assigned = False
            for dosen, data in slot_dosen.items():
                if assigned or tim["Bidang PKM"] not in data["bidang"]:
                    continue
                jumlah_tim_dosen.setdefault(dosen, {})
                for hari, sesi_list in data["jadwal"].items():
                    jumlah_tim_dosen[dosen].setdefault(hari, {})
                    for sesi in sesi_list:
                        sesi_range = sesi["range"]
                        jumlah_tim_dosen[dosen][hari].setdefault(sesi_range, 0)
                        if jumlah_tim_dosen[dosen][hari][sesi_range] >= MAKS_TIM_PER_DOSEN_PER_SESI:
                            continue
                        if sesi["slots"]:
                            hasil.append({
                                "Dosen": dosen,
                                "Hari": hari,
                                "Sesi": sesi_range,
                                "Jam": sesi["slots"].pop(0),
                                "Ketua": tim["Nama Ketua"],
                                "NRP": tim["NRP"],
                                "Bidang": tim["Bidang PKM"],
                                "Lokasi": data["lokasi"]
                            })
                            jumlah_tim_dosen[dosen][hari][sesi_range] += 1
                            assigned = True
                            break
                    if assigned:
                        break

        # ==========================
        # EXCEL OUTPUT IDENTIK
        # ==========================
        wb = Workbook()
        del wb["Sheet"]

        center = Alignment(horizontal="center", vertical="center")
        border = Border(*(Side(style="thin"),) * 4)

        fill_dosen = PatternFill("solid", fgColor="3d85c6")
        fill_hari = PatternFill("solid", fgColor="9fc5e8")
        fill_lokasi = PatternFill("solid", fgColor="fff2cc")

        TABLE_WIDTH = 6
        HEADER_HEIGHT = 4
        MAX_BARIS = MAKS_TIM_PER_DOSEN_PER_SESI
        TABLE_HEIGHT = HEADER_HEIGHT + MAX_BARIS

        grouped = {}
        for h in hasil:
            grouped.setdefault(h["Hari"], {}).setdefault(h["Dosen"], {}).setdefault(h["Sesi"], []).append(h)

        for hari in sorted(grouped):
            ws = wb.create_sheet(hari)
            table_idx = 0
            daftar = [(s, d, i) for d, sd in grouped[hari].items() for s, i in sd.items()]
            daftar.sort(key=lambda x: jam_mulai_sesi(x[0]))

            for sesi, dosen, items in daftar:
                sc = 1 + (table_idx % MAX_TABLE_PER_ROW) * TABLE_WIDTH
                sr = 1 + (table_idx // MAX_TABLE_PER_ROW) * (TABLE_HEIGHT + 1)

                ws.merge_cells(
                    start_row=sr,
                    start_column=sc,
                    end_row=sr,
                    end_column=sc+4
                )
                ws.cell(sr, sc, dosen).fill = fill_dosen
                ws.cell(sr, sc).alignment = center

                ws.merge_cells(
                    start_row=sr+1,
                    start_column=sc,
                    end_row=sr+1,
                    end_column=sc+4
                )
                ws.cell(sr+1, sc, f"{hari}, {sesi}").fill = fill_hari
                ws.cell(sr+1, sc).alignment = center

                ws.merge_cells(
                    start_row=sr+2,
                    start_column=sc,
                    end_row=sr+2,
                    end_column=sc+4
                )
                ws.cell(sr+2, sc, items[0]["Lokasi"]).fill = fill_lokasi
                ws.cell(sr+2, sc).alignment = center

                headers = ["No", "KSN", "Jam", "Nama Ketua", "Bidang"]
                for i, h in enumerate(headers):
                    ws.cell(sr+3, sc+i, h).alignment = center

                ws.merge_cells(
                    start_row=sr+4,
                    start_column=sc+1,
                    end_row=sr+4+MAX_BARIS-1,
                    end_column=sc+1
                )

                for i in range(MAX_BARIS):
                    r = sr+4+i
                    ws.cell(r, sc, i+1)
                    if i < len(items):
                        ws.cell(r, sc+2, items[i]["Jam"])
                        ws.cell(r, sc+3, items[i]["Ketua"])
                        ws.cell(r, sc+4, items[i]["Bidang"])

                for r in range(sr, sr+4+MAX_BARIS):
                    for c in range(sc, sc+5):
                        ws.cell(r, c).border = border

                table_idx += 1

        # ==========================
        # SHEET TAMBAHAN
        # ==========================
        ws_tim = wb.create_sheet("Tim Belum Terplot")
        ws_tim.append(["NRP", "Nama Ketua", "Bidang PKM"])
        terplot = {h["NRP"] for h in hasil}
        for _, r in df_tim.iterrows():
            if r["NRP"] not in terplot:
                ws_tim.append([r["NRP"], r["Nama Ketua"], r["Bidang PKM"]])

        ws_dosen = wb.create_sheet("Dosen Belum Terplot")
        ws_dosen.append(["Nama Dosen", "Hari", "Sesi Jam", "Jam Tidak Terplot", "Lokasi"])
        for d, data in slot_dosen.items():
            for h, sesi_list in data["jadwal"].items():
                for s in sesi_list:
                    slot = [x["Jam"] for x in hasil if x["Dosen"] == d and x["Hari"] == h and x["Sesi"] == s["range"]]
                    sisa = hitung_sisa_jam(s["range"], slot)
                    if sisa:
                        ws_dosen.append([d, h, s["range"], sisa, data["lokasi"]])

        # ==========================
        # REKAP
        # ==========================
        ws_rekap = wb.create_sheet("Rekap")
        ws_rekap.append(["REKAP JADWAL BIMBINGAN KOMUNAL"])
        ws_rekap.merge_cells(
            start_row=1,
            start_column=1,
            end_row=1,
            end_column=6
        )
        ws_rekap.cell(1,1).alignment = center

        df_hasil = pd.DataFrame(hasil)

        ws_rekap.append([])
        ws_rekap.append(["Jumlah Tim per Hari per Bidang PKM"])
        pivot = pd.pivot_table(df_hasil, index="Hari", columns="Bidang", values="Ketua", aggfunc="count", fill_value=0)
        ws_rekap.append(["Hari"] + list(pivot.columns))
        for h, v in pivot.iterrows():
            ws_rekap.append([h] + list(v))

        ws_rekap.append([])
        ws_rekap.append(["Jumlah Tim per Hari"])
        ws_rekap.append(["Hari", "Jumlah Tim"])
        for h, c in df_hasil.groupby("Hari")["Ketua"].count().items():
            ws_rekap.append([h, c])

        ws_rekap.append([])
        ws_rekap.append(["Jumlah Dosen per Hari"])
        ws_rekap.append(["Hari", "Jumlah Dosen"])
        for h, c in df_hasil.groupby("Hari")["Dosen"].nunique().items():
            ws_rekap.append([h, c])

        ws_rekap.append([])
        ws_rekap.append(["Jumlah Tim per Dosen"])
        ws_rekap.append(["Nama Dosen", "Jumlah Tim"])
        for d, c in df_hasil.groupby("Dosen")["Ketua"].count().items():
            ws_rekap.append([d, c])

        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        st.download_button("⬇️ Download Jadwal Excel", buffer, OUTPUT_FILE)
        st.success("Penjadwalan selesai dan output identik dengan kode Python pertama")
